# Generated by Django 4.1 on 2023-05-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('SELF SERVICE', 'Self service'), ('HAMBURGUERIA', 'Hamburgueria'), ('SUSHI', 'Sushi')], default='', max_length=100)),
                ('nota', models.CharField(max_length=10)),
                ('informacoes_adicionais', models.CharField(blank=True, max_length=150, null=True)),
                ('localizacao', models.CharField(max_length=150)),
                ('contato', models.CharField(max_length=150)),
            ],
        ),
    ]
