# Generated by Django 4.1 on 2023-05-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0002_alter_restaurante_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='horario_funcionamento',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
