# Generated by Django 4.1 on 2023-05-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0003_restaurante_horario_funcionamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/'),
        ),
    ]
